# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QSizePolicy
import datetime as dt
import core, sys
import pandas as pd


class Ui_MainWindow(object):

    day = int(dt.date.today().strftime("%d"))
    month = int(dt.date.today().strftime("%m"))
    year = int(dt.date.today().strftime("%Y"))


    def setupUi(self, MainWindow, app1):

        V = app1.desktop().screenGeometry()
        self.height1 = int(V.height())
        self.width1 = int(V.width())
        # def __init__(self, df)


        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(self.width1/2, self.height1/2)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(self.width1/9.5, 0, self.width1/3, self.height1/18))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.inSource = QtWidgets.QLineEdit(self.centralwidget)
        self.inSource.setGeometry(QtCore.QRect((self.width1*0.06), (self.height1/7), 231, 31))
        self.inSource.setText("")
        self.inSource.setObjectName("inSource")
        self.inDate = QtWidgets.QDateEdit(self.centralwidget)
        self.inDate.setGeometry(QtCore.QRect((self.width1*0.3125), (self.height1/7), 111, 31))
        self.inDate.setDate(QtCore.QDate(self.year, self.month , self.day))
        self.inDate.setObjectName("inDate")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect((self.width1*0.22), (self.height1*0.074), (self.width1*0.052), (self.height1/36)))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.inAmount = QtWidgets.QSpinBox(self.centralwidget)
        self.inAmount.setGeometry(QtCore.QRect((self.width1*0.2), (self.height1/7), 51, 31))
        self.inAmount.setMaximum(100000)
        self.inAmount.setDisplayIntegerBase(10)
        self.inAmount.setObjectName("inAmount")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect((self.width1*0.11), (self.height1/9), (self.width1/32), (self.height1*0.03)))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect((self.width1*0.2),(self.height1/9), (self.width1/32), (self.height1*0.013)))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect((self.width1*0.3125), (self.height1/9), 47, 14))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect((self.width1*0.22), (self.height1/5), (self.width1*0.06), (self.height1/36)))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect((self.width1*0.11), (self.height1/4), (self.width1/32), (self.height1*0.03)))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect((self.width1*0.2), (self.height1/4), (self.width1/32), (self.height1*0.013)))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect((self.width1*0.3125), (self.height1/4), 47, 14))
        self.label_9.setObjectName("label_9")
        self.outSource = QtWidgets.QLineEdit(self.centralwidget)
        self.outSource.setGeometry(QtCore.QRect((self.width1*0.06), (self.height1/3.5), 231, 31))
        self.outSource.setText("")
        self.outSource.setObjectName("outSource")
        self.outAmount = QtWidgets.QSpinBox(self.centralwidget)
        self.outAmount.setGeometry(QtCore.QRect((self.width1*0.2), (self.height1/3.5), 51, 31))
        self.outAmount.setMaximum(100000)
        self.outAmount.setObjectName("outAmount")
        self.outDate = QtWidgets.QDateEdit(self.centralwidget)
        self.outDate.setGeometry(QtCore.QRect((self.width1*0.3125), (self.height1/3.5), 111, 31))
        self.outDate.setDate(QtCore.QDate(self.year, self.month , self.day))
        self.outDate.setObjectName("outDate")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect((self.width1*0.42187), (self.height1/7), 61, 31))
        self.saveButton.setObjectName("saveButton")
        self.saveButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton_2.setGeometry(QtCore.QRect((self.width1*0.42187), (self.height1/3.5), 61, 31))
        self.saveButton_2.setObjectName("saveButton_2")
        self.pushExport = QtWidgets.QPushButton(self.centralwidget)
        self.pushExport.setGeometry(QtCore.QRect((self.width1*0.42187), (self.height1/2.5), 75, 23))
        self.pushExport.setObjectName("pushExport")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, (self.height1/3), (self.width1/0.31), (self.height1*0.0277)))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.salaryCount = QtWidgets.QLabel(self.centralwidget)
        self.salaryCount.setGeometry(QtCore.QRect(40, (self.height1/2.5), 121, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.salaryCount.setFont(font)
        self.salaryCount.setText("")
        self.salaryCount.setAlignment(QtCore.Qt.AlignCenter)
        self.salaryCount.setObjectName("salaryCount")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect((self.width1*0.2), (self.height1/3), (self.width1*0.145), (self.height1*0.0277)))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.balanceCheck = QtWidgets.QLabel(self.centralwidget)
        self.balanceCheck.setGeometry(QtCore.QRect((self.width1*0.2), (self.height1/2.5), 121, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.balanceCheck.setFont(font)
        self.balanceCheck.setText("")
        self.balanceCheck.setAlignment(QtCore.Qt.AlignCenter)
        self.balanceCheck.setObjectName("balanceCheck")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 670, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        # self.saveButton.clicked.connect(self.show_popup)#
        # self.saveButton_2.clicked.connect(self.show_popup)
        self.saveButton.clicked.connect(self.press_save)
        self.saveButton_2.clicked.connect(self.press_save_2)
        self.pushExport.clicked.connect(self.press_export)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Personal Finance Management"))
        self.label.setText(_translate("MainWindow", "Personal Finance Management!"))
        self.label_2.setText(_translate("MainWindow", "Income"))
        self.label_3.setText(_translate("MainWindow", "Topic"))
        self.label_4.setText(_translate("MainWindow", "Amount"))
        self.label_5.setText(_translate("MainWindow", "Date"))
        self.label_6.setText(_translate("MainWindow", "Expense"))
        self.label_7.setText(_translate("MainWindow", "Topic"))
        self.label_8.setText(_translate("MainWindow", "Amount"))
        self.label_9.setText(_translate("MainWindow", "Date"))
        self.saveButton.setText(_translate("MainWindow", "SAVE"))
        self.saveButton_2.setText(_translate("MainWindow", "SAVE"))
        self.pushExport.setText(_translate("MainWindow", "EXPORT"))
        self.label_10.setText(_translate("MainWindow", "Days Remain for Salary:"))
        self.label_11.setText(_translate("MainWindow", "Remaning Balance:"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
    
    def show_popup(self):
        msg = QMessageBox()
        msg.setWindowTitle('Save.')
        msg.setText('Saved!!')
        msg.setIcon(QMessageBox.Information)
        msg.setStandardButtons(QMessageBox.Save)
        msg.exec_()

    def popup_button(self):
        self.show()

    def press_save(self):
        core.get_file()
        engine = core.Calculations(core.not_df)
        engine.income_data(self.inSource.text(), int(self.inAmount.text()), self.inDate.text())
        engine.export()
        self.inSource.setText("")
        self.inAmount.setValue(0)
        self.inDate.setDate(QtCore.QDate(self.year, self.month , self.day))
        self.show_balance()

    def press_save_2(self):
        core.get_file()
        engine = core.Calculations(core.not_df)
        engine.expense_data(self.outSource.text(), int(self.outAmount.text()), self.outDate.text())
        engine.export()
        self.outSource.setText("")
        self.outAmount.setValue(0)
        self.outDate.setDate(QtCore.QDate(self.year, self.month , self.day))

        self.show_balance()

    def press_export(self):
        core.get_file()
        engine = core.Calculations(core.not_df)
        engine.export_to_pdf()

    def show_balance(self):
        core.get_file()
        engine = core.Calculations(core.not_df)
        self.balanceCheck.setText(str(engine.df['Total'].values[-1]))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    core.get_file()
    engine = core.Calculations(core.not_df)

    ui.setupUi(MainWindow, app)
    MainWindow.show()


    sys.exit(app.exec_())